os: linux
arch:
  - arm64
language: node_js
node_js:
  - "20"  
  - "16"
  - "15"
  - "14"
  - "12"
  - "10"
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
script:
  - npm run lint

